### ISSUE TITLE
When generating gold paths, some games default to 'train' set

### ISSUE THREAD

**Issue by PeterAJansen** [cognitiveailab/TextWorldExpress#1]
Currently there is a bug where, for several of the games, if the user calls `mkGameWithGoldPath()`, it will generate the correct gold path, but ignore the fold parameter when regenerating the game.  The effect of this is that the gold path will be correct, but the returned game will be generated using the `train` fold instead of the user-selected fold (e.g. `train`, `dev`, `test`). 

https://github.com/cognitiveailab/TextWorldExpress/blob/9a5738e0a3c6ecb406d8e5399f0b82cfb1489235/simulator/src/main/scala/textworldexpress/games/CoinGame.scala#L888

A fix should be out shortly.

**Comment by MarcCote** [comment]
I believe this was fixed in cdb0dfa ?
