### ISSUE TITLE
Cookingworld game generation freezes when numLocations is low.

### ISSUE THREAD

**Issue by MarcCote** [cognitiveailab/TextWorldExpress#4]
There are two issues with the code for placing recipe ingredients in the world.
https://github.com/cognitiveailab/TextWorldExpress/blob/main/simulator/src/main/scala/textworldexpress/games/KitchenGame.scala#L833-L846
```java
      // Try to place the object in a random location
      breakable {
        var attempts: Int = 0
        while (attempts < 100) {
          val randLocationIdx = r.nextInt(validLocations.length)
          val generationLocation = validLocations(randLocationIdx)
          if (allObjects.contains(generationLocation)) {
            allObjects(generationLocation).addObject(recipeItem)
            objectsAdded.append(recipeItem)
            //println ("Added " + recipeItem.name + " to " + generationLocation)
            break()
          }
        }
        throw new RuntimeException("ERROR: Unable to place recipe ingredient: " + recipeItem.toString)
      }
```

The first one is the variable `attempts` is never incremented, so the while loop will never terminate. But even when adding the `attempts += 1`, an exception is likely to be thrown and it is never caught.

@PeterAJansen what should we do here? 

- Catch the error, then regenerate a new recipe.
or
- When choosing the ingredients for the recipe, check if they can be placed.

Reported by @xingdi-eric-yuan.

**Comment by PeterAJansen** [comment]
Thanks -- fixed in https://github.com/cognitiveailab/TextWorldExpress/pull/3
