### ISSUE TITLE
List of objects

### ISSUE THREAD

**Issue by xingdi-eric-yuan** [cognitiveailab/TextWorldExpress#9]
Hello! Is there an easy way in TWX (specifically, the cooking games) I can get a list of all possible object names from the game API? 

It would be even better if object types can also be available (e.g, `fridge: container`).

I think this can be obtained by running a few games and parse the admissible actions, just want to see if there's any chance the API already had this. 

Thanks!

**Comment by PeterAJansen** [comment]
Hi @xingdi-eric-yuan , thanks for this request!

Would you need (1) a list of all possible objects that currently exist in the current instance of the game that the agent is playing, or (2) a list of all possible objects that might ever appear in any game across train, dev, and test sets?  

(1) should be very straightforward to implement, but (2) would be more challenging and require a bit of thought.

**Comment by xingdi-eric-yuan** [comment]
Thanks for the reply @PeterAJansen !

Just had a chat with @MarcCote , we decide to start with just food ingredients (all possible food items in all games), for which I'll just parse [this file](https://github.com/cognitiveailab/TextWorldExpress/blob/dev/textworld_express/cooking_world.json). We will see in the future what else is needed.

**Comment by xingdi-eric-yuan** [comment]
Thanks for the reply @PeterAJansen !

Just had a chat with @MarcCote , we decide to start with just food ingredients (all possible food items in all games), for which I'll just parse [this file](https://github.com/cognitiveailab/TextWorldExpress/blob/dev/textworld_express/cooking_world.json). We will see in the future what else is needed. Closing this issue for now.
